apiVersion: v2
name: reference-spring-boot-mvn-jkube-workflow
description: |
  A Helm chart for Kubernetes to deploy the Ploigos Workflow (Typical) for the
  "reference-spring-boot-mvn-jkube" application.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
- name: ploigos-workflow-tekton-pipeline-typical
  version: "~0.22.0"
  repository: "https://ploigos.github.io/ploigos-charts"
